### ISSUE TITLE
Shouldly.ShouldAssertException: [AzurePipelines.TestLogger.Tests.ClientMessage (x)] should be [AzurePipelines.TestLogger.Tests.ClientMessage (y)]

### ISSUE THREAD

**Issue by icnocop** [daveaglick/AzurePipelines.TestLogger#4]
Hi Dave.

I forked and cloned the project, but I get the following error when the tests are run:
```
  X CreateParents [73ms]
  Error Message:
   Shouldly.ShouldAssertException : [AzurePipelines.TestLogger.Tests.ClientMessage (-971002351)]
    should be
[AzurePipelines.TestLogger.Tests.ClientMessage (1542145733)]
    but was not
    difference
[*AzurePipelines.TestLogger.Tests.ClientMessage (-971002351)*]
  Stack Trace:
     at Shouldly.ShouldlyCoreExtensions.AssertAwesomely[T](T actual, Func`2 specifiedConstraint, Object originalActual, Object originalExpected, Func`1 customMessage, String shouldlyMethod)
   at Shouldly.ShouldBeTestExtensions.ShouldBe[T](IEnumerable`1 actual, IEnumerable`1 expected, Boolean ignoreOrder, Func`1 customMessage)
   at Shouldly.ShouldBeTestExtensions.ShouldBe[T](IEnumerable`1 actual, IEnumerable`1 expected, Boolean ignoreOrder)
   at AzurePipelines.TestLogger.Tests.LoggerQueueTests.CreateParents() in C:\github\icnocop\AzurePipelines.TestLogger\tests\AzurePipelines.TestLogger.Tests\LoggerQueueTests.cs:line 201
```

[build.txt](https://github.com/daveaglick/AzurePipelines.TestLogger/files/4073616/build.txt)

The error messages aren't very helpful and so I had to debug the test to figure out which properties are actually different.

![Actual Client Message Not As Expected](https://user-images.githubusercontent.com/507649/72561024-18f45080-385d-11ea-8a3d-e3521b76b76d.png)

Windows 10 Enterprise Version 1909 (OS Build 18363.535) 64-bit
Visual Studio Enterprise 2019 16.4.1
TimeZone: PST
Locale: English - US

Thank you.

**Comment by daveaglick** [comment]
_Finally_ getting around to merging these in! Thanks a lot for running this to ground all the way to a fix.

**Comment by daveaglick** [comment]
I was able to reproduce the failures locally and confirmed the fix - thanks again!
